<a href="https://colab.research.google.com/github/sovunia-hub/mathematical-modeling-of-applied-problems/blob/main/1_simple_iteration_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = 0
b = 1
N = 3
u1 = lambda x: 3 * x / 4
h = np.abs(b - a) / N
x = np.arange(N) * h + h / 2 + a
A = np.zeros((N, N))
for i in range(N):
  for j in range(N):
    if i == j:
      A[i, j] = h * x[i] * x[j] + 1
    else:
      A[i, j] = h * x[i] * x[j]
u2 = np.linalg.solve(A, x)
print(u2)
print(u1(x))

[0.12587413 0.37762238 0.62937063]
[0.125 0.375 0.625]


In [2]:
def findU(N):
  h = np.abs(b - a) / N
  x = np.arange(N) * h + h / 2 + a
  A = np.zeros((N, N))
  I = np.eye(N)
  kol = 0
  for i in range(N):
    for j in range(N):
      if i == j:
        A[i, j] = h * x[i] * x[j] + 1
      else:
        A[i, j] = h * x[i] * x[j]
  u3 = np.zeros(N)
  B = I - A
  while True:
    kol+=1
    prevu3 = u3
    u3 = B @ u3 + x
    d = np.linalg.norm(u3 - prevu3) / np.linalg.norm(x)
    #print(u3, '\t', np.abs(d))
    if d < 0.0001:
      return u3, kol

In [7]:
findU(10)

(array([0.03752283, 0.1125685 , 0.18761416, 0.26265983, 0.33770549,
        0.41275116, 0.48779682, 0.56284249, 0.63788815, 0.71293382]),
 10)

In [6]:
N = 10
h = np.abs(b - a) / N
x = np.arange(N) * h + h / 2 + a
delt = sum(np.abs(u1(x) - findU(N)[0])) / sum(np.abs(u1(x)))
print(delt)

0.0006088640980693838
